const userTypes = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_IN_ERROR: "SIGN_IN_ERROR",
  REGISTRATION_SUCCESS: "REGISTRATION_SUCCESS",
  REGISTRATION_ERROR: "REGISTRATION_ERROR",
};

export default userTypes;
